[workspace]
authors = ["Neclow <neilclow24@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "thesis_defence"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
post_install = "Rscript src/post_install.R"

[dependencies]
ipykernel = ">=7.1.0,<8"
seaborn = ">=0.13.2,<0.14"
pandas = ">=2.3.3,<3"
numpy = "<2.3"
ipywidgets = ">=8.1.8,<9"
h5py = ">=3.15.1,<4"
bioconductor-ggtree = { version = ">=3.14.0,<4", channel = "bioconda" }
iqtree = { version = ">=3.0.1,<4", channel = "bioconda" }
clustalo = { version = ">=1.2.4,<2", channel = "bioconda" }
r-devtools = ">=2.4.6,<3"
r-dplyr = ">=1.1.4,<2"
r-janitor = ">=2.2.1,<3"
r-magrittr = ">=2.0.4,<3"
r-readxl = ">=1.4.5,<2"
r-stringr = ">=1.6.0,<2"
r-tidybayes = ">=3.0.7,<4"
r-tidyr = ">=1.3.2,<2"
r-phangorn = ">=2.12.1,<3"
r-treedist = ">=2.11.1,<3"
r-phytools = ">=2.5_2,<3"
r-cairo = ">=1.7_0,<2"


[pypi-dependencies]
phylo2vec = "==1.6.0"
